<html lang="en">
<?php
include ('dbconnect.inc.php');
include("islogged.inc.php");

if (isset($_POST['submitted'])) {
    $fname = $_POST['fname'];
    $sname = $_POST['sname'];
    $username = $_POST['username'];
    $email = $_POST['email'];
    $password = $_POST['password'];

    if (is_null($_POST['fname'])) {
        $fname = FALSE;
        die('<p>Please enter your first name</p>');
    }
    if (is_null($_POST['sname'])) {
        $sname = FALSE;
        die('<p>Please enter your surname</p>');
    }
    if (is_null($_POST['username'])) {
        $username = FALSE;
        die('<p>Please enter your username</p>');
    }
    if (is_null($_POST['email'])) {
        $email = FALSE;
        die('<p>PLease enter valid email address</p>');
    }
    if (is_null($_POST['password'])) {
        $password = FALSE;
        die('<p> please enter a password</p>');
    }
    if (!preg_match('/^[a-zA-Z0-9]*$/', $username)) {
        die("Invalid username. Only alphanumeric characters are allowed.");
    }

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        die("Invalid email format");
    }

    if ($password) {
        //If omitted, a random salt will be generated by password_hash() for each password hashed. This is the intended mode of operation."
        // https://www.php.net/manual/en/function.password-hash.php
        $password = password_hash($password, PASSWORD_DEFAULT);
    }
   
    $sql = $dbconnect->prepare("INSERT INTO userdata (username, fname, sname, email, password) VALUES(?, ?, ?, ?, ?)");
    $sql->bind_param('sssss', $username, $fname, $sname, $email, $password);
    $sql->execute();
    echo "New record has beed added";
    $sql->close();
    $dbconnect->close();
}
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="core.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">
    <link rel="icon" type="icon/png" href="images/logo1.png">
    <style>
        header {
            background-image: url(images/banner_admin.png);
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
    <title> Ubiquitec || International </title>
    <link rel="icon" href="demo_icon.gif" type="image/gif" sizes="16x16">
</head>

<body>
<nav class="sticky">
    <div class="topnav" id="myTopnav">
        <a href="index.php">Home</a>
        <a href="products.php">Products</a>
        <a href="support.php">Support</a>
        <a href="contact.php">Contact</a>
        <a href="Projects.php">Projects</a>
        <a href="admin.php">Admin</a>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i></a>
    </div>

</nav>
<script>
    function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
            x.className += " responsive";
        } else {
            x.className = "topnav";
        }
    }
</script>
<header>
    <h1 class="slogan-top">for life</h1>
    <h1 class="slogan-mid"> a job,</h1>
    <h1 class="slogan-bottom">Ubiquitec,</h1>
    <div class="clear"></div>
</header>

<article>
    <h1 style="margin-top: 6vh; margin-bottom: 5vh">Ubiquitec Admin Page</h1>

    <h3>Projects <span>
                <h5>No active projects</h5>
            </span></h3>

    <h3>Create New Account</h3>
    <table class="new_user" style="margin-left: 4%;">
        <form action="admin.php" method="post" enctype="multipart/form-data" name="register">

            <tr>
                <td><label>First Name:</label></td>
                <td><input name="fname" type="text"></td>
            </tr>
            <tr>
                <td><label>Surname:</label></td>
                <td><input name="sname" type="text"></td>
            </tr>
            <tr>
                <td><label>Username:</label></td>
                <td><input name="username" type="text"></td>
            </tr>
            <tr>
                <td><label>Email:</label></td>
                <td><input name="email" type="text"></td>
            </tr>
            <tr>
                <td><label>Password:</label></td>
                <td><input name="password" type="text"></td>
            </tr>
            <tr>
                <td></td>
                <td><input name="register" type="submit" value="Register"></td>
                <td><input name="submitted" type="hidden" value="true"></td>
            </tr>
        </form>
    </table>
</article>


<footer style="color: #ffffff;text-align: center;">
    &copy;Ubiquitec International
</footer>
</body>

</html>